"""empty message

Revision ID: 193205c3f96f
Revises: 21d9c2a8f819
Create Date: 2019-07-19 17:49:47.984627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '193205c3f96f'
down_revision = '21d9c2a8f819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_user_identification', table_name='user')
    op.drop_column('user', 'identification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('identification', mysql.VARCHAR(collation='utf8mb4_bin', length=255), nullable=True))
    op.create_index('ix_user_identification', 'user', ['identification'], unique=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
