"""empty message

Revision ID: 26520ecda310
Revises: a6a50b47a5e8
Create Date: 2019-07-19 10:20:49.129563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26520ecda310'
down_revision = 'a6a50b47a5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identification', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_identification'), 'user', ['identification'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('user_abstracts',
    sa.Column('user.id', sa.Integer(), nullable=False),
    sa.Column('abstract.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abstract.id'], ['abstract.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user.id', 'abstract.id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_abstracts')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_identification'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
