"""empty message

Revision ID: 50886ae56746
Revises: 
Create Date: 2019-08-07 17:49:30.254488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50886ae56746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Integer(), nullable=True),
    sa.Column('abstract', mysql.LONGTEXT(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('non_rct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abstract_pmid'), 'abstract', ['pmid'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neg_sentence', mysql.LONGTEXT(), nullable=True),
    sa.Column('pos_sent', mysql.LONGTEXT(), nullable=True),
    sa.Column('clause', mysql.LONGTEXT(), nullable=True),
    sa.Column('len_of_neg', sa.Integer(), nullable=True),
    sa.Column('len_of_pos', sa.Integer(), nullable=True),
    sa.Column('len_of_clause', sa.Integer(), nullable=True),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_abstracts',
    sa.Column('user.id', sa.Integer(), nullable=False),
    sa.Column('abstract.id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['abstract.id'], ['abstract.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user.id', 'abstract.id')
    )
    op.create_table('nsentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', mysql.LONGTEXT(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', mysql.LONGTEXT(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pclause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause', mysql.LONGTEXT(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['psentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pclause')
    op.drop_table('psentence')
    op.drop_table('nsentence')
    op.drop_table('user_abstracts')
    op.drop_table('response')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_abstract_pmid'), table_name='abstract')
    op.drop_table('abstract')
    # ### end Alembic commands ###
