"""empty message

Revision ID: a6a50b47a5e8
Revises: b5eb90ec2b09
Create Date: 2019-07-12 11:04:37.152911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a6a50b47a5e8'
down_revision = 'b5eb90ec2b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neg_sentence', mysql.LONGTEXT(), nullable=True),
    sa.Column('pos_sent', mysql.LONGTEXT(), nullable=True),
    sa.Column('clause', mysql.LONGTEXT(), nullable=True),
    sa.Column('len_of_neg', sa.Integer(), nullable=True),
    sa.Column('len_of_pos', sa.Integer(), nullable=True),
    sa.Column('len_of_clause', sa.Integer(), nullable=True),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('nsentence', sa.Column('response_id', sa.Integer(), nullable=True))
    op.drop_constraint('nsentence_ibfk_1', 'nsentence', type_='foreignkey')
    op.create_foreign_key(None, 'nsentence', 'response', ['response_id'], ['id'])
    op.drop_column('nsentence', 'abstract_id')
    op.add_column('psentence', sa.Column('response_id', sa.Integer(), nullable=True))
    op.drop_constraint('psentence_ibfk_1', 'psentence', type_='foreignkey')
    op.create_foreign_key(None, 'psentence', 'response', ['response_id'], ['id'])
    op.drop_column('psentence', 'abstract_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('psentence', sa.Column('abstract_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'psentence', type_='foreignkey')
    op.create_foreign_key('psentence_ibfk_1', 'psentence', 'abstract', ['abstract_id'], ['id'])
    op.drop_column('psentence', 'response_id')
    op.add_column('nsentence', sa.Column('abstract_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'nsentence', type_='foreignkey')
    op.create_foreign_key('nsentence_ibfk_1', 'nsentence', 'abstract', ['abstract_id'], ['id'])
    op.drop_column('nsentence', 'response_id')
    op.drop_table('response')
    # ### end Alembic commands ###
