"""empty message

Revision ID: aabdd3ab252a
Revises: 0fe533e200df
Create Date: 2019-09-09 19:00:11.414103

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aabdd3ab252a'
down_revision = '0fe533e200df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_abstracts', 'user', ['user.id'], ['id'])
    op.create_foreign_key(None, 'user_abstracts', 'abstract', ['abstract.id'], ['id'])
    op.drop_column('user_abstracts', 'abstract_id')
    op.drop_column('user_abstracts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_abstracts', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('user_abstracts', sa.Column('abstract_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_abstracts', type_='foreignkey')
    op.drop_constraint(None, 'user_abstracts', type_='foreignkey')
    # ### end Alembic commands ###
