"""empty message

Revision ID: b5eb90ec2b09
Revises: 
Create Date: 2019-07-11 17:57:17.007556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5eb90ec2b09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abstract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pmid', sa.Integer(), nullable=True),
    sa.Column('abstract', mysql.LONGTEXT(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('non_rct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abstract_pmid'), 'abstract', ['pmid'], unique=True)
    op.create_table('nsentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', mysql.LONGTEXT(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('psentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sentence', mysql.LONGTEXT(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('abstract_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['abstract_id'], ['abstract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pclause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clause', mysql.LONGTEXT(), nullable=True),
    sa.Column('label', sa.Boolean(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['psentence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pclause')
    op.drop_table('psentence')
    op.drop_table('nsentence')
    op.drop_index(op.f('ix_abstract_pmid'), table_name='abstract')
    op.drop_table('abstract')
    # ### end Alembic commands ###
